### PR TITLE
feat : address tab

### PR DESCRIPTION
**Pull request by mohammed-sas**
1.Added address-card in address management tab
2.csb link : https://sv5n5.csb.app/Address%20Page/address.html

Screen Shot 2022-02-04 at 4 18 22 PM

### CODE REVIEW

**Review by Abhijeet43 — APPROVED** [review]
Looks Good!

**Review by Abhijeet43 — COMMENTED** [review]
Just a suggestion: Hey @mohammed-sas you can add spacing between the address and where button section begins

**Review by Husain01 — APPROVED** [review]
Looks good to go 👍🏻

**Comment by mohammed-sas** [comment]
> Just a suggestion: Hey @mohammed-sas you can add spacing between the address and where button section begins

sure

**Pull request merged**
