### PR TITLE
feat : Navbar

### PR DESCRIPTION
**Pull request by mohammed-sas**
Screen Shot 2022-02-02 at 11 31 52 AM

### CODE REVIEW

**Review by Abhijeet43 — APPROVED** [review]
Looks good Mohammed!!!!!

**Review by Kevin-Solomon — APPROVED** [review]

**Comment by mohammed-sas** [comment]
> Looks good Mohammed!!!!!

thank you abhijeet

**Review by RahullRawat — APPROVED** [review]
All good mohammed

**Comment by mohammed-sas** [comment]
> All good mohammed

thank you

**Pull request merged**
